version: "3.8"

services:
    postgres:
        image: postgres:13
        container_name: postgres-container
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel_network

volumes:
    pgdata:

networks:
    laravel_network:
        driver: bridge
